"use client";

import { Navbar } from "@/components/Navbar";
import { motion } from "framer-motion";
import { Brain } from "lucide-react";
import { Shield } from "lucide-react";
import { Activity } from "lucide-react";
import { Code } from "lucide-react";
import { Database } from "lucide-react";
import { Mail } from "lucide-react";
import { Github } from "lucide-react";
import { ChevronLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function AboutPage() {
  return (
    <div className="relative min-h-screen overflow-x-hidden">
      <Navbar />
      
      {/* Background Decor */}
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-teal-900/20 via-background to-background" />
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px] -z-10" />

      <main className="container mx-auto px-4 pt-32 pb-20 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Link href="/" className="inline-flex items-center text-teal-400 hover:text-teal-300 transition-colors mb-8 group">
            <ChevronLeft className="w-4 h-4 mr-1 group-hover:-translate-x-1 transition-transform" />
            Back to Home
          </Link>

          <h1 className="text-5xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-500">
            About NeuralPath AI
          </h1>

          <div className="prose prose-invert prose-slate max-w-none space-y-12">
            
            <section>
              <h2 className="text-2xl font-semibold text-white flex items-center gap-3 mb-4">
                <Brain className="w-6 h-6 text-primary" /> Project Overview
              </h2>
              <p className="text-slate-300 text-lg leading-relaxed">
                NeuralPath AI is a specialized diagnostic assistant designed to bridge the gap between deep learning research and clinical utility. 
                The platform utilizes advanced convolutional neural networks to analyze MRI scans, identifying pathologies like Glioma, Meningioma, and Pituitary tumors with high precision.
              </p>
            </section>

            <div className="grid md:grid-cols-2 gap-8">
              <div className="p-6 rounded-3xl bg-white/5 border border-white/10">
                <h3 className="text-white font-bold mb-3 flex items-center gap-2">
                  <Database className="w-5 h-5 text-teal-400" /> Dataset
                </h3>
                <p className="text-sm text-slate-400">
                  The model was trained on a curated dataset of over 7,000 brain MRI images, ensuring robust feature extraction across various tumor types and imaging protocols.
                </p>
              </div>
              <div className="p-6 rounded-3xl bg-white/5 border border-white/10">
                <h3 className="text-white font-bold mb-3 flex items-center gap-2">
                  <Code className="w-5 h-5 text-teal-400" /> Architecture
                </h3>
                <p className="text-sm text-slate-400">
                  Built on a fine-tuned VGG-16 backbone with custom dense layers, optimized for medical feature saliency and Grad-CAM interpretability.
                </p>
              </div>
            </div>

            <section>
              <h2 className="text-2xl font-semibold text-white flex items-center gap-3 mb-4">
                <Shield className="w-6 h-6 text-rose-400" /> Medical Disclaimer
              </h2>
              <div className="p-6 rounded-3xl bg-rose-500/5 border border-rose-500/20">
                <p className="text-slate-300 text-sm italic m-0">
                  NeuralPath AI is strictly a research and educational project. The predictions generated by this system are for informational purposes only and do not constitute medical advice or a formal diagnosis. 
                  Always seek the counsel of a licensed physician or neurosurgeon for medical concerns.
                </p>
              </div>
            </section>

            <section className="pt-8 border-t border-white/10">
              <h2 className="text-2xl font-semibold text-white mb-6">The Developer</h2>
              <div className="flex flex-col md:flex-row items-center gap-8 bg-slate-900/40 p-8 rounded-[3rem] border border-white/5">
                <div className="w-24 h-24 rounded-full bg-gradient-to-br from-teal-500 to-primary flex items-center justify-center text-3xl font-bold text-white shadow-lg shadow-teal-500/20">
                  SS
                </div>
                <div className="text-center md:text-left flex-1">
                  <h3 className="text-xl font-bold text-white mb-1">Sahil Sharma</h3>
                  <p className="text-teal-400 text-sm mb-4">AI Research & Software Engineering</p>
                  <p className="text-slate-400 text-sm leading-relaxed mb-6">
                    A Computer Science undergraduate focused on the intersection of deep learning and medical imaging. 
                    NeuralPath AI represents an exploration into making AI models explainable and accessible to medical professionals.
                  </p>
                  <div className="flex flex-wrap justify-center md:justify-start gap-4">
                    <Link href="https://github.com/En1gma1708" target="_blank">
                      <Button variant="outline" size="sm" className="gap-2 border-white/10 hover:bg-white/5">
                        <Github className="w-4 h-4" /> GitHub
                      </Button>
                    </Link>
                    <Link href="mailto:sharmasahil.work@gmail.com">
                      <Button variant="outline" size="sm" className="gap-2 border-white/10 hover:bg-white/5">
                        <Mail className="w-4 h-4" /> Email Me
                      </Button>
                    </Link>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </motion.div>
      </main>

      <footer className="border-t border-white/5 py-12">
        <div className="container mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Activity className="w-5 h-5 text-primary" />
            <span className="font-bold">NeuralPath AI</span>
          </div>
          <p className="text-slate-600 text-xs">
            (c) {new Date().getFullYear()} Sahil Sharma. MIT Licensed Research Project.
          </p>
        </div>
      </footer>
    </div>
  );
}
