import os
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from dotenv import load_dotenv

# Load .env variables
load_dotenv()

def generate_medical_report(prediction: str, confidence: float, summary: str):
    template = """You are an expert Neuroradiologist AI. 
Generate a comprehensive, formal Neuroradiology Report based on the MRI scan analysis provided below.

Strictly format your response using standard Medical/Radiological Reporting structure using Markdown. 
Use ## for headings, ** for bold, * for italics, and - for bullet points. Ensure there are clear blank lines between sections.

INPUT DATA:
- Primary Finding (Classification): {prediction}
- AI Diagnostic Confidence: {confidence}%
- Brief Summary: {summary}

REQUIRED REPORT STRUCTURE:
## NEURORADIOLOGY REPORT

**Patient Demographics:** [Anonymized / Not Provided]
**Date of Exam:** [Current Date]
**Exam Type:** MRI Brain w/o IV Contrast

### CLINICAL INDICATION
*Patient presented for evaluation of suspected intracranial pathology. AI screening protocol activated.*

### TECHNIQUE
*Automated Deep Learning (VGG-16/CNN) Diagnostic Screening of MRI Brain.*

### FINDINGS
(Provide a detailed, professional paragraph explaining the typical radiological appearance of the detected {prediction}. Use bold for key terms.)

### IMPRESSION
1. **{prediction}**: (State the primary finding and the AI confidence of {confidence}%).
2. (Add a bullet point about typical clinical significance or symptoms).
3. (Add a bullet point recommending clinical correlation or further imaging).

---
*Disclaimer: This report is generated by NeuralPath AI as an assistive screening tool and does not constitute a final medical diagnosis. Clinical correlation by a certified radiologist is required.*
"""
    
    prompt = ChatPromptTemplate.from_template(template)
    
    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    if not api_key:
        return "Error: GROQ_API_KEY is not set in the backend environment. Cannot generate report."
    
    try:
        model = ChatGroq(model="llama-3.1-8b-instant", groq_api_key=api_key)
        chain = prompt | model
        
        ans = chain.invoke({
            "prediction": prediction,
            "confidence": f"{confidence:.2f}",
            "summary": summary
        })
        return ans.content
    except Exception as e:
        return f"Error generating report: {str(e)}"
