import os
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from dotenv import load_dotenv

from retriever import retriever

# Load .env variables
load_dotenv()

def generate_medical_report(prediction: str, confidence: float, summary: str):
    template = """You are an expert Neuroradiologist AI. 
Generate a comprehensive, formal Neuroradiology Report based on the MRI scan analysis provided below.

Strictly format your response using standard Medical/Radiological Reporting structure using Markdown. 
Use ## for headings, ** for bold, * for italics, and - for bullet points. Ensure there are clear blank lines between sections.

INPUT DATA:
- Primary Finding (Classification): {prediction}
- AI Diagnostic Confidence: {confidence}%
- Brief Summary: {summary}

REQUIRED REPORT STRUCTURE:
## NEURORADIOLOGY REPORT

**Patient Demographics:** [Anonymized / Not Provided]
**Date of Exam:** [Current Date]
**Exam Type:** MRI Brain w/o IV Contrast

### CLINICAL INDICATION
*Patient presented for evaluation of suspected intracranial pathology. AI screening protocol activated.*

### TECHNIQUE
*Automated Deep Learning (VGG-16/CNN) Diagnostic Screening of MRI Brain.*

### FINDINGS
(Provide a detailed, professional paragraph explaining the typical radiological appearance of the detected {prediction}. Use bold for key terms.)

### IMPRESSION
1. **{prediction}**: (State the primary finding and the AI confidence of {confidence}%).
2. (Add a bullet point about typical clinical significance or symptoms).
3. (Add a bullet point recommending clinical correlation or further imaging).

---
*Disclaimer: This report is generated by NeuralPath AI as an assistive screening tool and does not constitute a final medical diagnosis. Clinical correlation by a certified radiologist is required.*
"""
    
    prompt = ChatPromptTemplate.from_template(template)
    
    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    if not api_key:
        return "Error: GROQ_API_KEY is not set in the backend environment. Cannot generate report."
    
    try:
        model = ChatGroq(model="openai/gpt-oss-20b", groq_api_key=api_key)
        chain = prompt | model
        
        ans = chain.invoke({
            "prediction": prediction,
            "confidence": f"{confidence:.2f}",
            "summary": summary
        })
        return ans.content
    except Exception as e:
        return f"Error generating report: {str(e)}"


def radiologist_chat(message: str, prediction: str, confidence: float, probabilities: dict, chat_history: list):
    # Grounded retrieval (Phase 2b): pull relevant passages from the curated
    # medical reference corpus (backend/rag_corpus/) instead of relying
    # solely on the model's parametric knowledge, which has no citation and
    # a real hallucination risk for medical claims. Retrieval is best-effort
    # - an empty result (no chunk clears the similarity threshold) is a
    # valid outcome, not an error; the chat still answers, just ungrounded
    # for that specific message.
    retrieved = retriever.retrieve(message, top_k=3)
    if retrieved:
        context_block = "\n\n".join(
            f"[Source: {c['source']}, section \"{c['heading']}\"]\n{c['text']}"
            for c in retrieved
        )
        grounding_instructions = (
            "REFERENCE MATERIAL (cite this when it's relevant to the question; "
            "do not invent facts beyond what's here or your own general medical "
            "knowledge - if the reference material contradicts a guess you might "
            "otherwise make, defer to the reference material):\n"
            f"{context_block}\n"
        )
    else:
        grounding_instructions = (
            "No specific reference material was retrieved for this question - "
            "answer from general medical knowledge, and don't claim a citation "
            "that doesn't exist.\n"
        )

    system_prompt = f"""You are Dr. NeuralPath, an expert AI Neuroradiologist assistant.
You are helping a user understand their brain MRI scan results. Be professional, empathetic, and clear.

SCAN CONTEXT (always reference this when relevant):
- Classification: {prediction}
- AI Confidence: {confidence:.1f}%
- Probability Breakdown: {', '.join(f'{k}: {v:.1f}%' for k, v in probabilities.items())}

{grounding_instructions}
RULES:
- Answer questions about the scan results, brain conditions, next steps, and general neuroradiology.
- When you use the reference material above, mention the source briefly (e.g. "per clinical reference material...").
- Always remind the user this is AI-assisted analysis and they should consult a real physician.
- Be concise (2-4 paragraphs max). Use simple language a patient can understand.
- If asked something completely unrelated to medicine, politely redirect.
- Never make a definitive diagnosis. Use phrases like "the AI screening suggests" or "this may indicate".
"""

    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    if not api_key:
        return "I'm sorry, the AI service is not configured. Please contact support."

    try:
        model = ChatGroq(model="openai/gpt-oss-20b", groq_api_key=api_key)
        
        from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
        messages = [SystemMessage(content=system_prompt)]
        
        for msg in chat_history[-10:]:  # Keep last 10 messages for context
            if msg["role"] == "user":
                messages.append(HumanMessage(content=msg["content"]))
            else:
                messages.append(AIMessage(content=msg["content"]))
        
        messages.append(HumanMessage(content=message))
        
        response = model.invoke(messages)
        return response.content
    except Exception as e:
        return f"I encountered an error processing your question. Please try again. ({str(e)})"
